# # starts a postgres instance
# version: "3.6"
# services:
#   postgres:
#     image: postgres:13
#     ports:
#       - "5432:5432" # expose pg on port 5465 to not collide with pg from elsewhere
#     restart: always
#     volumes:
#       - db_data:/var/lib/postgresql_dev/data
#     environment:
#       POSTGRES_HOST_AUTH_METHOD: trust
#       POSTGRES_DB: trpc-vue-vite-ssr
#       POSTGRES_USER: default
#       POSTGRES_PASSWORD: default
# volumes:
#   db_data:
# starts a mysql instance
version: '3.6'

services:
  mysql_dev:
    image: mysql:5.7
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=default
      - MYSQL_ROOT_PASSWORD=default
      - MYSQL_DATABASE=trpc-vue-vite-ssr-dev
      - 'TZ=Asia/Shanghai'
  redis_dev:
    image: redis:7
    ports:
      - 6379:6379
    environment:
      - PASSWORD=123456
    volumes:
      - ./redis:/data
volumes:
  db_data:
    driver: local
